# Generated by Django 4.2.7 on 2024-02-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buluntu_name', models.CharField(max_length=50, verbose_name='Küçük Buluntu Adı')),
            ],
            options={
                'verbose_name': 'Buluntu Form',
                'verbose_name_plural': 'Buluntu Formu',
            },
        ),
    ]
