# Generated by Django 4.2.7 on 2024-02-18 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buluntu', '0001_initial'),
        ('buluntuForm', '0002_toprakornegi_c14'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedGenelField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buluntu.animaltype', verbose_name='Hayvan Türü')),
                ('linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_general_field', to='buluntuForm.formlar')),
                ('piece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buluntu.piece', verbose_name='Eser')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buluntu.status', verbose_name='Durum')),
            ],
        ),
    ]
