# Generated by Django 4.2.7 on 2024-02-18 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buluntu', '0001_initial'),
        ('buluntuForm', '0003_relatedgenelfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedgenelfield',
            name='animalType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buluntu.animaltype', verbose_name='Hayvan Türü'),
        ),
        migrations.AlterField(
            model_name='relatedgenelfield',
            name='piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buluntu.piece', verbose_name='Eser'),
        ),
        migrations.AlterField(
            model_name='relatedgenelfield',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buluntu.status', verbose_name='Durum'),
        ),
    ]
