# Generated by Django 4.2.7 on 2024-02-18 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buluntu', '0001_initial'),
        ('buluntuForm', '0004_alter_relatedgenelfield_animaltype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedBezemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buluntu.bezeme')),
                ('bezemeAlani', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buluntu.bezemealani')),
                ('bezemeTuru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buluntu.bezemeturu')),
                ('linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_bezemes_field', to='buluntuForm.formlar')),
            ],
        ),
    ]
