# Generated by Django 4.2.7 on 2024-02-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buluntuForm', '0005_relatedbezemes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50, verbose_name='Değer')),
            ],
        ),
    ]
