# Generated by Django 4.2.7 on 2024-02-18 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buluntuForm', '0006_customfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfields',
            name='linked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_custom_field', to='buluntuForm.formlar'),
        ),
    ]
