# Generated by Django 4.2.7 on 2024-02-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buluntuForm', '0007_customfields_linked'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfields',
            name='fieldType',
            field=models.CharField(default='', max_length=50, verbose_name='Veri'),
        ),
        migrations.AddField(
            model_name='customfields',
            name='fieldVisible',
            field=models.BooleanField(default=True, verbose_name='Gösterilsin mi'),
        ),
    ]
